name: toughest
description: A new Flutter project.
version: 2.0.2+4

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  share_plus: any
  shrink_sidemenu: ^2.0.0+2-null-safety
  carousel_slider: ^5.0.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_driver:
    sdk: flutter
  mockito: null
  test: null


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/local.json
    - assets/confetti.json


  fonts:
    - family: Acme
      fonts:
        - asset: assets/font/Acme-Regular.ttf
          weight: 600
    - family: Josefin Sans
      fonts:
        - asset: assets/font/JosefinSans-Regular.ttf
          weight: 200

    - family: Roboto
      fonts:
       - asset: assets/font/Roboto-Regular.ttf
       - asset: assets/font/Roboto-Bold.ttf
         weight: 700
       - asset: assets/font/Roboto-Italic.ttf
         style: italic

